name: panchanga_calendar
description: A stable Madhwa Panchanga App.
version: 1.0.1+2
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  firebase_core: ^3.0.0 #
  cloud_firestore: ^5.0.0 #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21